const profiles = {
  children: {
    key: "children",
    name: "Kids Mode",
    emoji: "👶",
    description: "Fun & colorful experience",
    theme: {
      "--bg": "#fff9f0",
      "--card": "#ffffff",
      "--text": "#2d2d2d",
      "--sub": "#888888",
      "--accent": "#ff9500",
      "--msg-user": "#ff9500",
      "--msg-ai": "#f0f0f0",
      "--msg-ai-text": "#2d2d2d",
      "--font": "'Comic Neue', cursive",
      "--font-size": "18px",
      "--radius": "20px",
      "--input-h": "52px",
      "--header-bg": "rgba(255,249,240,0.95)",
      "--border": "#ffddaa",
    },
    placeholder: "What do you want to know? 😊",
    welcomeTitle: "Hi there! 👋",
    welcomeSub: "I'm your fun friend! Ask me anything!",
    suggestions: [
      { emoji: "🦁", label: "Animals" },
      { emoji: "🌈", label: "Colors" },
      { emoji: "🚀", label: "Space" },
      { emoji: "🎮", label: "Games" },
    ],
    autoSpeak: true,
    fontSize: "large",
  },

  elderly: {
    key: "elderly",
    name: "Senior Mode",
    emoji: "🧓",
    description: "Large text, voice-first, easy to use",
    theme: {
      "--bg": "#1a1a2e",
      "--card": "#16213e",
      "--text": "#f0f0f0",
      "--sub": "#aaaaaa",
      "--accent": "#e94560",
      "--msg-user": "#0f3460",
      "--msg-ai": "#16213e",
      "--msg-ai-text": "#f0f0f0",
      "--font": "'Atkinson Hyperlegible', sans-serif",
      "--font-size": "22px",
      "--radius": "16px",
      "--input-h": "64px",
      "--header-bg": "rgba(26,26,46,0.95)",
      "--border": "#0f3460",
    },
    placeholder: "Type your question here...",
    welcomeTitle: "Hello! I'm here to help. 😊",
    welcomeSub: "Take your time. Ask me anything you need.",
    suggestions: [],
    autoSpeak: true,
    fontSize: "xlarge",
  },

  special: {
    key: "special",
    name: "Special Mode",
    emoji: "🌟",
    description: "Simple, calm & supportive",
    theme: {
      "--bg": "#0d1b2a",
      "--card": "#1b2838",
      "--text": "#e8f4f8",
      "--sub": "#8ab4c8",
      "--accent": "#4fc3f7",
      "--msg-user": "#2d6a9f",
      "--msg-ai": "#1b2838",
      "--msg-ai-text": "#e8f4f8",
      "--font": "'Atkinson Hyperlegible', sans-serif",
      "--font-size": "17px",
      "--radius": "16px",
      "--input-h": "52px",
      "--header-bg": "rgba(13,27,42,0.95)",
      "--border": "#2d6a9f",
    },
    placeholder: "Talk to me anytime...",
    welcomeTitle: "Hello! 🌟",
    welcomeSub: "I'm here for you. Take all the time you need.",
    suggestions: [
      { emoji: "😊", label: "Feel good" },
      { emoji: "🆘", label: "Need help" },
      { emoji: "🙋", label: "Question" },
    ],
    autoSpeak: true,
    fontSize: "medium",
  },

  normal: {
    key: "normal",
    name: "Standard Mode",
    emoji: "🧑",
    description: "Clean modern chat experience",
    theme: {
      "--bg": "#0f0f13",
      "--card": "#1a1a24",
      "--text": "#ffffff",
      "--sub": "#999999",
      "--accent": "#6c63ff",
      "--msg-user": "#6c63ff",
      "--msg-ai": "#1e1e2e",
      "--msg-ai-text": "#ffffff",
      "--font": "'Nunito', sans-serif",
      "--font-size": "15px",
      "--radius": "16px",
      "--input-h": "52px",
      "--header-bg": "rgba(15,15,19,0.95)",
      "--border": "#6c63ff",
    },
    placeholder: "Message Pula...",
    welcomeTitle: "Hey there! 👋",
    welcomeSub: "Ask me anything — I'm ready to help.",
    suggestions: [],
    autoSpeak: false,
    fontSize: "normal",
  },
};

export default profiles;
